# Here frontend is wait for backend-svc with port 80 
apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  initContainers:
  - name: wait-for-backend
    image: busybox
    command: ['sh', '-c']
    args: ["until nc -z backend-svc 80; do echo 'Waiting for backend...'; sleep 2; done; echo 'Backend is ready!'"]
  containers:
  - name: frontend
    image: busybox
    command: ['sh', '-c', 'echo "Frontend running"; sleep 3600']
    ports:
    - containerPort: 8080
