apiVersion: v1
kind: ReplicationController
metadata:
  name: sample-rc
  labels:
    app: redis
spec:
  replicas: 2
  selector:
    app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 80
