apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: app-config

# Inside the container
# /etc/config/APP_ENV
# /etc/config/DB_NAME
