apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-probe
  template:
    metadata:
      labels:
        app: redis-probe
    spec:
      containers:
        - name: redis
          image: redis:8
          ports:
            - containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
