apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: environment
            operator: In
            values:
            - production
            - staging
  containers:
  - name: frontend
    image: nginx
